### ISSUE TITLE
Лишние файлы

### ISSUE THREAD

**Issue by s3rius** [Python-internship/AviDjango#1]
В репозиторий просочились ненужные файлы, избавься от них.
По заданию не должно быть иных Django-приложений, кроме goods. Читайте задание внимательнее.

**Comment by askopintsev** [comment]
Правильно ли понимаю, что в репозиторий не нужно коммитить папку пакета проекта "avidjango"? В таком случае возникает вопрос, как поддержать работоспособность приложения в репозитории без этой папки.

**Comment by askopintsev** [comment]
Обновил структуру
