### ISSUE TITLE
Обновление данных в get_queryset

### ISSUE THREAD

**Issue by Kolaer** [Python-internship/AviDjango#3]
Заметил что обновляются данные в `get_queryset`. Это не очень хорошо в плане поддержки кода, лучше такие вещи делать в соответсвующих методах (`post`, `put`, `patch`)

https://github.com/Python-internship/AviDjango/blob/1ef7e449e415df2a3e43963bba11d6a3e1b5b309/goods/goods_service/views.py#L59

**Comment by askopintsev** [comment]
@Kolaer Поправил в: https://github.com/Python-internship/AviDjango/pull/7
Не знаю, правильно ли указал Павла ревьювером, но доступен только он как участник проекта
