### ISSUE TITLE
Связь между тегами и объявлениями

### ISSUE THREAD

**Issue by Kolaer** [Python-internship/AviDjango#4]
Логичнее будет сделать `ManyToMany` в объявлении. Тогда будет чуть очевиднее работать с ORM

https://github.com/Python-internship/AviDjango/blob/1ef7e449e415df2a3e43963bba11d6a3e1b5b309/goods/goods_service/models.py#L20

**Comment by askopintsev** [comment]
@Kolaer Поправил в: https://github.com/Python-internship/AviDjango/pull/7
Не знаю, правильно ли указал Павла ревьювером, но доступен только он как участник проекта
