### ISSUE TITLE
Странная структура url'ов

### ISSUE THREAD

**Issue by Kolaer** [Python-internship/AviDjango#5]
Запросы для получения/обновления информации о сущности лучше выводить на один url, а отличать их по типу запроса (GET, POST, ...)

https://github.com/Python-internship/AviDjango/blob/1ef7e449e415df2a3e43963bba11d6a3e1b5b309/goods/goods_service/urls.py#L9

**Comment by askopintsev** [comment]
@Kolaer Поправил в: https://github.com/Python-internship/AviDjango/pull/7
Не знаю, правильно ли указал Павла ревьювером, но доступен только он как участник проекта
