### ISSUE TITLE
Фильтрация

### ISSUE THREAD

**Issue by Kolaer** [Python-internship/AviDjango#6]
Фильтрацию лучше делать одним запросом: для пользователя так будет гораздо удобнее и логичнее

https://github.com/Python-internship/AviDjango/blob/1ef7e449e415df2a3e43963bba11d6a3e1b5b309/goods/goods_service/urls.py#L11

**Comment by askopintsev** [comment]
@Kolaer Поправил в: https://github.com/Python-internship/AviDjango/pull/7
Не знаю, правильно ли указал Павла ревьювером, но доступен только он как участник проекта
